[package]
name = "div-os"
version = "0.2.0"
edition = "2021"
authors = ["Divyansh Sirohi"]

[dependencies]
# Basic synchronization primitives
spin = "0.9"

# Lazy static initialization
lazy_static = { version = "1.4", features = ["spin_no_std"] }

# Bit manipulation
bitflags = "2.4"

# RISC-V low-level access
riscv = "0.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
